### PR TITLE
Changes for call by external UI

### PR DESCRIPTION
**Pull request by martindurant**
Ability to point to a specific prefix directory instead of a named environment.

### CODE REVIEW

**Comment by goanpeca** [comment]
@martindurant I am making the changes in a separate branch to include the desired functionality. 

The path you followed is incorrect as the `self._prefix` refers to the `ROOT_PREFIX` (where conda lives) and not the `--prefix` command from conda. I will try to rename variables so that this is clear.

**Comment by ccordoba12** [comment]
Closing then?

**Comment by goanpeca** [comment]
I will leave open until I make the push @ccordoba12

**Comment by goanpeca** [comment]
@martindurant, @ccordoba12 I made the changes to the conda-manager and will push directly to master by the end of the day.

Closing.

**Comment by ccordoba12** [comment]
:+1:

**Pull request closed without merging**
