### PR TITLE
Make conda-manager work with PyQt5 and improve tests

### PR DESCRIPTION
**Pull request by ccordoba12**
The previous test only checked that installation was correct. Now we check that the app starts and stops correctly.

---

Also:
- Do some cleanup on `qthelpers`
- Add tests for AppVeyor

### CODE REVIEW

**Comment by ccordoba12** [comment]
I think this is ready to be merged. Tests are only failing on PyQt5, but to fix that we need a new release of `qtpy`.

**Comment by goanpeca** [comment]
@ccordoba12 LGTM, feel free to merge ;-)

**Comment by ccordoba12** [comment]
I'll merge this one after a new version of qtpy is released, just to verify that tests are passing.

**Comment by goanpeca** [comment]
@ccordoba12 
- Conda package
  https://anaconda.org/spyder-ide/qtpy/files
- And pip ready
  https://pypi.python.org/pypi/QtPy/

**Pull request merged**
